# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x05proto\"r\n\x17\x41\x63\x63ountPersonalShowInfo\x12+\n\nbasic_info\x18\x01 \x01(\x0b\x32\x17.proto.AccountInfoBasic\x12*\n\x0cprofile_info\x18\x02 \x01(\x0b\x32\x14.proto.AvatarProfile\"@\n\x10\x41\x63\x63ountInfoBasic\x12\x11\n\tbanner_id\x18\x0b \x01(\r\x12\x19\n\x11weapon_skin_shows\x18  \x03(\r\":\n\rAvatarProfile\x12\x11\n\tavatar_id\x18\x01 \x01(\r\x12\x16\n\x0e\x65quiped_skills\x18\x04 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTPERSONALSHOWINFO']._serialized_start=21
  _globals['_ACCOUNTPERSONALSHOWINFO']._serialized_end=135
  _globals['_ACCOUNTINFOBASIC']._serialized_start=137
  _globals['_ACCOUNTINFOBASIC']._serialized_end=201
  _globals['_AVATARPROFILE']._serialized_start=203
  _globals['_AVATARPROFILE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
